### ISSUE TITLE
Support destructuring from Ember global.

### ISSUE THREAD

**Issue by rwjblue** [GavinJoyce/babel-plugin-remove-functions#13]
Input:

```js
const { 
  assert,
  deprecate
} = Ember;

deprecate('message', test);
assert('message', test);
console.log(message);
```

Expected output:

```js
console.log(message);
```

(though I don't really think we care if we leave the destructuring around)

**Comment by GavinJoyce** [comment]
I've added support for non-nested destructured imports in https://github.com/GavinJoyce/babel-plugin-remove-functions/pull/16.

I've also opened an issue for [possibly supporting nested destructured imports](https://github.com/GavinJoyce/babel-plugin-remove-functions/issues/19).
