### ISSUE TITLE
Do we need to support additional forms of import statement?

### ISSUE THREAD

**Issue by GavinJoyce** [GavinJoyce/babel-plugin-remove-functions#2]
We currently support removing functions that are imported as follows:

```js
import Ember from 'ember';

export default Ember.Component.extend({
  didInsertElement() {
    console.log('didInsertElement');
    Ember.debug('didInsertElement'); //will be removed
  }
});
```

Do we need to support other types of import? eg:

```js
import { debug } from 'ember'?
```

Should we handle global uses of `Ember` too?

**Comment by rwjblue** [comment]
We should support the current ember-cli-shims also (they are at the very least "intimate API's"):

``` js
import { warn, run } from 'ember-debug';
import { assert } from 'ember-metal/utils';
import { deprecate, deprecateFunc } from 'ember-deprecations';
```

**Comment by GavinJoyce** [comment]
These are now supported: https://github.com/GavinJoyce/babel-plugin-remove-functions/tree/master/test/fixtures/destructuring
